### ISSUE TITLE
Webform CiviCRM Integration error on status report

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/webform_civicrm#16]
As of yesterday I've noticed a Webform CiviCRM Integration error on my Backdrop status report:

> Version error
> The versions of the Webform CiviCRM Integration, Webform, CiviCRM enabled are not compatible. See the Webform CiviCRM Integration project page for version compatibility

I've not noticed this error before and am not sure why it's suddenly appeared. I'm running Backdrop 1.7.2, Webform CiviCRM 1.x-1.0.1, Webform 1.x-1.6.0 and CiviCRM 4.7.23.

@herbdool, have you noticed this anywhere?

**Comment by herbdool** [comment]
In https://github.com/backdrop-contrib/webform_civicrm/blob/1.x-1.x-backdrop/webform_civicrm.module you can see the constants at the top:

```
define('WEBFORM_CIVICRM_CIVICRM_VERSION_MIN', '4.4');
define('WEBFORM_CIVICRM_CIVICRM_VERSION_MAX', FALSE);

define('WEBFORM_CIVICRM_WEBFORM_VERSION', '1.x-1.1.0');
```

In `_webform_civicrm_status()` it checks the versions. I checked and for CiviCRM module it outputs: `1.x-4.7` and Webform module is `1.x-1.6.0`. So you'll need to update the constant to: `define('WEBFORM_CIVICRM_CIVICRM_VERSION_MIN', '1.x-4.7');` and make a new release. I recall this recent change by CiviCRM to the way they version the module.

**Comment by jackaponte** [comment]
Thanks so much for this info, @herbdool! I'm going to try to get this done and create a new release in the near future.

**Comment by herbdool** [comment]
@jackaponte if you like I can create the PR and you can test and create the release

**Comment by jackaponte** [comment]
Much appreciation, @herbdool; that said, I really need to learn how to create pull requests, test and create releases properly. This seems like a good change to try that out on! But if I linger too long please feel free to supersede that aim of mine for the sake of the project. :)

**Comment by herbdool** [comment]
@jackaponte alright! In case you need a refresher. Make a fork of this project (or update your fork from the main project by making a PR from backdrop-contrib to yours). Then make a new branch based on the 1.x-... branch -- I usually call it the same as the issue number.

Then edit webform_civicrm.module to update the civicrm version to 1.x-4.7. Then make a PR from your issue branch back to 1.x- branch on backdrop-contrib. And then someone can review your PR--good to get a second person to review if possible. 

Once it's in, then you can create the new release. If there are no major code changes I would use a minor number. Currently it's 1.x-1.0.1 and the new one could be 1.x-1.0.2.

**Comment by jackaponte** [comment]
Thanks again for all the pointers, @herbdool! With your guidance I've created pull request #17 which I've tested and which is now ready for a second review. It would be awesome if you (or someone else who happens to see this?) could give it a quick look!

**Comment by herbdool** [comment]
@jackaponte I've reviewed it and it looks good! Feel free to merge and make a new minor release. I guess it would be 1.x-1.0.2. You can look at previous ones for a good format: https://github.com/backdrop-contrib/webform_civicrm/releases

**Comment by jackaponte** [comment]
[Done!](https://github.com/backdrop-contrib/webform_civicrm/releases/tag/1.x-1.0.2) Thanks for all the help, Herb. :)
