### ISSUE TITLE
Remove dependency on libraries?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform_civicrm#18]
Unless I'm mistaken, this module doesn't actually require the libraries module. This is the only place that uses it (I think):
https://github.com/backdrop-contrib/webform_civicrm/blob/1.x-1.x-backdrop/includes/contact_component.inc#L952-L960

Maybe we can remove that dependency? Is there any downside to just using CiviCRM's copy right away instead of as a fallback?

**Comment by herbdool** [comment]
Given that libraries module is discouraged in Backdrop perhaps you're right @laryn. I don't see much downside but perhaps @colemanw has some insight?

**Comment by colemanw** [comment]
Yep. @laryn can you go ahead and put in a PR to remove that conditional and the dependency.

**Comment by laryn** [comment]
@colemanw Sure, happy to -- but do you mean to do a PR on the Drupal version, or the Backdrop version, or both?

**Comment by colemanw** [comment]
Let's start with backdrop.

**Comment by laryn** [comment]
@colemanw See how that looks to you.

**Comment by herbdool** [comment]
@laryn looks good. I'll merge. For now @colemanw isn't a maintainer of this project though we could certainly add him if he wishes.

**Comment by laryn** [comment]
Gotcha, thanks @herbdool!
