### ISSUE TITLE
Remove dependency on options_element

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/webform_civicrm#29]
The functionality is now in Backdrop core.

**Comment by jackaponte** [comment]
Does [this commit](https://github.com/backdrop-contrib/webform_civicrm/commit/770bf0e5c9767c9b9cdc4aac8ed50b6db6ced2b0) take care of this issue, @herbdool? (Thank you for that commit, by the way!)

**Comment by herbdool** [comment]
You're welcome!
