### ISSUE TITLE
Merge in 7.x-4.24, 7.x-4.25 and 7.x-4.26

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/webform_civicrm#30]
https://www.drupal.org/project/webform_civicrm/releases/7.x-4.24

I'm creating this issue as suggested by @herbdool as a way to get in the swing of properly co-maintaining Webform CiviCRM. Advice on next steps for getting this update merged in would be much appreciated, though I can also work on figuring it out on my own.

7.x-4.25 and 7.x-4.26 are also available for Drupal 7; let me know if you think it's best to merge them all in at once, Herb!

**Comment by herbdool** [comment]
Okay, let's get started! You got the first couple steps: create issue for a d7 release and got the notes for the release.

We keep the numbering similar to D7 but add another point for bug fixes. So this will be 1.x-4.24.0.

1. To your fork of the BD webform_civicrm repo add the Drupal git repo as another remote. 
2. Then use for fetch to get the code (but not merged). 
3. Make a new branch 1.x-4.24.0
4. Then merge the exact release tag into this branch: git merge 7.x-4.24.
5. You may have merge conflicts that you have to resolve. Either you accept the incoming changes, keep the existing ones or manually edit to keep some of each. Some conflicts result because of renamed functions or variables to Backdrop.
6. Make sure there are no Drupal names or variables or variable_get/set sneaking in.
7. Commit the changes to your branch and push to your fork.
8. In GitHub go to your fork and create a PR. In the PR comment put a link to this issue.
9. Let me know so I can review your PR.

That's it more or less!

**Comment by jackaponte** [comment]
Awesome, thanks for this step-by-step guide Herb! Some of it is familiar, but it's been a long while since I've done this kind of work, so this is very helpful.

I hope to work more on this later this week and get you a pull request soon!

**Comment by laryn** [comment]
I'm running into [an issue that appears to be fixed in 4.24](https://lab.civicrm.org/marketing/civicrm-website/issues/99), which brought me here. Any luck on this @jackaponte?

**Comment by jackaponte** [comment]
Sadly no luck yet, @laryn. :( Since my hopeful post in February I've been sucked down into other work and haven't gotten started here yet. I hope to start soon, but certainly don't expect anyone to be waiting around on my availability if they can get to it first!

**Comment by laryn** [comment]
Thanks @jackaponte (I know how it goes). I am going to try to do 4.24 quickly now and see if it solves my problem. Will PR here.

**Comment by laryn** [comment]
@herbdool I just created a PR for code review merging in the changes from the Drupal side. Tested to the extent that it solves the error I was hitting earlier but obviously a good code review from you would be needed.

https://github.com/backdrop-contrib/webform_civicrm/pull/31

**Comment by jackaponte** [comment]
> Thanks @jackaponte (I know how it goes). I am going to try to do 4.24 quickly now and see if it solves my problem. Will PR here.

Many thanks @laryn, both for the understanding and for creating that PR for 4.24!

**Comment by laryn** [comment]
For the record, I think this is the list of commands I used:

> git remote set-url origin https://github.com/laryn/webform_civicrm.git

> git remote add upstream https://git.drupalcode.org/project/webform_civicrm.git

> git fetch upstream

> git pull origin 1.x-4.x

> git checkout 1.x-4.x

> git merge upstream/7.x-4.x

At this point it merged and had just a few conflicts that I had to clean up.

**Comment by laryn** [comment]
I suppose I should have done all this in a new branch instead of 1.x-4.x but luckily I was working on my personal fork. 😉

**Comment by herbdool** [comment]
@laryn thanks!

I usually merge the released tag instead of the branch. That way we know exactly which commits and the Backdrop release more closely matches D7's. There might be new commits that haven't been released yet. It might not be a big deal this time though.

I can do a code review if you and/or @jackaponte are able to test.

**Comment by laryn** [comment]
Makes sense. Do you want me to make a new PR from the release tag?

I am using this version on a site in production and haven't noticed any
issues.

L.

**Comment by herbdool** [comment]
Let's stick with this. It's more about being able to be clear in the release notes. We'll need to note the exact range of commits as part of the release, which can be done.

**Comment by herbdool** [comment]
@laryn on second thought, can you make a new PR using the 7.x-4.26 release tag? I'm having a hard time matching up the commits between https://github.com/colemanw/webform_civicrm/commits/7.x-5.x?before=793a0188a315ae1382fba7f30a27758bcaac1dfb+35 and your PR. There's a commit in your PR that doesn't appear in the source - perhaps it was removed. It'll be easier if we know the exact range of commits.

**Comment by laryn** [comment]
@herbdool your link goes to the 5.x branch. Is the missing PR here?
https://github.com/colemanw/webform_civicrm/commits/7.x-4.x

If not I'll try to redo the PR from 4.26.

**Comment by jackaponte** [comment]
Hmm, looking at https://github.com/colemanw/webform_civicrm/commits/7.x-4.x?before=1950aed68b0ddc3e04041ab9a89e87f9c10a4846+35 (which I think represents the 7.x-4.26 release) and https://github.com/backdrop-contrib/webform_civicrm/pull/31/commits (Laryn's PR), the PR also goes beyond the official 7.x-4.26 release, as @laryn notes in the overview. Do we want that for an official Backdrop release, or do we want it to be equal to the Drupal release? I'd guess the latter!

I have time and have needed to do this for a long time anyhow, so I'm going to go ahead and work on a PR for the 7.x-4.24 release, since it will fix the problem Laryn is having but is a smaller chunk of work than the jump to 7.x-4.26!

**Comment by jackaponte** [comment]
Hi Herb--I've finally done it, and it wasn't so bad, especially with no conflicts to resolve if I did this all properly. See pull request #32.

I've done a fair amount of testing in my local environment and could do another round of testing in another environment as well, but someone else's testing would probably be more helpful at this point!

If we get this pull request merged I'll try to move on to 7.x-4.25 ASAP. :)

**Comment by herbdool** [comment]
@jackaponte thank you! I've merged it. @laryn thanks for your work on this too. I've decided to merge the release by release to keep the history more organized.

If the next two releases happen soon I can still produce one release here with notes detailing that 3 D7 releases are included here.

**Comment by jackaponte** [comment]
Awesome, I'm glad that worked, thanks for merging the pull request, Herb!

> If the next two releases happen soon I can still produce one release here with notes detailing that 3 D7 releases are included here.

Ah, you mean produce one backdrop-contrib release for the three D7 releases at once? Sounds good to me!

I'm going to start working on 7.x-4.25 this week; should I start a new issue for that and close this one?

**Comment by jackaponte** [comment]
@herbdool I decided to just stick with this issue. :) Pull request #33 merging in Drupal 7.x-4.25 looks good to me after my code review and testing, but someone else should probably test it on their instance before we get it merged.

**Comment by jackaponte** [comment]
Thanks for merging PR #33 so quickly, @herbdool! I've created a new tiny PR #34 to fix a small error in my merge conflict resolution.

**Comment by jackaponte** [comment]
Just put in pull request #35, we're almost ready for that new release on backdropcms.org! :) As I noted on the PR, it was another easy merge, one instance of `drupal_set_message` to replace, no conflicts. Tested on my local, looks good from here!

**Comment by herbdool** [comment]
Thanks a bunch @jackaponte! I've merged all and I'll create a release.

**Comment by jackaponte** [comment]
Awesome, thanks! Very glad to be contributing more to this module's maintenance again. Now I just need to learn how to create a release myself. :)

Thanks for the help and encouragement, @herbdool and @laryn!

**Comment by herbdool** [comment]
@jackaponte the release is one of the easiest parts! You can do it all from the GUI here. I usually look at older releases for guidance on the format, including a list of changes or links to where people can find the changes.

**Comment by jackaponte** [comment]
Sweet, thanks for the encouragement @herbdool! Maybe I'll take care of the next release on here. :)
