### ISSUE TITLE
Add as maintainer?

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/webform_civicrm#4]
@jackaponte do you mind if I add myself as a maintainer? I'd like to get an official release of this so it can be listed on the Backdrop CMS site.

**Comment by jackaponte** [comment]
It would be amazing if you added yourself as a maintainer, @herbdool; I've got little module maintainer experience and have been too busy with other work to keep up with this! I've set you as an administrator on this GitHub project; feel free to add yourself to the README.md, and let me know if anything else is needed for you to be a full maintainer. Thank you SO much for offering to work on this!

**Comment by herbdool** [comment]
Thanks!
