### ISSUE TITLE
Listing this module in CiviCRM extensions directory

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform_civicrm#42]
We have a Backdrop-specific extensions directory page (linked from the extensions GUI in CiviCRM) but nothing in it. This module is the best candidate to date (I have a few more that I'll add in the next few weeks hopefully), but in case you are interested I thought I'd put the info here:

- Backdrop extensions/modules: https://civicrm.org/extensions/backdrop/
- Webform-CiviCRM example for Drupal: https://civicrm.org/extensions/webform-civicrm-integration

I thought of asking if the Drupal version could just be multi-tagged, but the maintainers are different, anyway...

**Comment by herbdool** [comment]
How do they get added to the directory?

**Comment by laryn** [comment]
https://civicrm.org/node/add/extension

**Comment by herbdool** [comment]
I've added it though now we've got a problem that Backdrop isn't available in the list of compatible CMS's. I've asked in the chat for help.

**Comment by jackaponte** [comment]
Thanks for creating the issue @laryn, and thanks for adding the module, @herbdool!

Could you update https://civicrm.org/extensions/webform-civicrm-for-backdrop to list me as a current maintainer as well? It'll encourage me to keep getting more proactive in my maintainership. :)

**Comment by laryn** [comment]
While you're editing the page again, it looks like the releases section at the bottom says "Drupal 7.x" for CMS compatibility:

![Screen Shot 2019-11-11 at 2 00 59 PM](https://user-images.githubusercontent.com/871421/68616954-bb720b00-048b-11ea-96af-91d5ae4a6d80.jpg)

**Comment by herbdool** [comment]
Someone added Backdrop as an option since I created it. So I've updated the release.

@jackaponte I've added you as maintainer.

**Comment by jackaponte** [comment]
Great, thanks @herbdool!
