### ISSUE TITLE
Update to match 7.x-5.1

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/webform_civicrm#47]
https://www.drupal.org/project/webform_civicrm/releases/7.x-5.1

https://github.com/colemanw/webform_civicrm/compare/7.x-5.0...7.x-5.1

**Comment by herbdool** [comment]
@jackaponte I've got a branch up with the changes. But I haven't had a chance to run manual or automated tests to make sure it's all still working. Would you have time to test?

**Comment by jackaponte** [comment]
@herbdool Thanks for getting that branch up! I should be able to test next week.

**Comment by jackaponte** [comment]
Hey @herbdool, was able to do some pretty thorough testing today -- manual only, I still haven't delved into automated testing very much! Are there automated tests already written for webform_civicrm that I could learn to run?

I caught a small syntax error right away and fixed it with that commit I just pushed to the `issue-47` branch. With that fix everything seems to be working properly to me!

**Comment by herbdool** [comment]
@jackaponte thanks! I'm not sure about the automated tests. I'll try to look at this tomorrow and hopefully get it merged/released this week.

**Comment by jackaponte** [comment]
Yay, thanks for getting that release out @herbdool!
