### ISSUE TITLE
Jack on sabbatical August through December

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/webform_civicrm#48]
@herbdool, happy to report that I'll be on sabbatical from my work at Palante beginning August 1 through December! I'll be returning to work in January 2021.

During that time I'm going to be as removed as I can get myself to be from most things tech, so I shouldn't be counted upon as a very reliable co-maintainer during that time. (After that time I hope to be a more reliable co-maintainer than I've been to date!)

Wanted to give you this heads up here in the issue queue so we can plan how to handle that (and maybe see if anyone would like to help co-maintain, at least short-term in my absence?)

What do you think?

**Comment by jackaponte** [comment]
To be more clear: I won't be able to do any co-maintaining from August through December! (Unless I have some epiphany and am called back to the tech world before my sabbatical is over, which seems unlikely, but who knows, this is 2020, anything can happen!)

**Comment by jackaponte** [comment]
Hi @herbdool, just wanted to check in once more about this; if you feel all set to handle maintenance while I'm gone, let me know and I'll close this issue! Otherwise I'll probably close it anyhow right before my sabbatical starts. :)

**Comment by herbdool** [comment]
Thanks for letting me know @jackaponte! Let's leave it open in case anyone sees and wants to help.

I say enjoy your break and being able to switch this off. Epiphany or no, I say take the whole time off and don't give this a second thought!

**Comment by jackaponte** [comment]
Thanks for that response @herbdool! Especially for the encouragement to truly take the whole time off, much appreciated. :)

**Comment by jackaponte** [comment]
Hello again @herbdool! I'm back from my sabbatical and will slowly be getting back into the groove of Backdrop stuff, this module's maintenance included. I'll close this ticket now since I'm back!
