### ISSUE TITLE
Merge 7.x-5.2 commits

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform_civicrm#50]
I'm having an issue on one of my sites and am curious if any of the commits from 7.x-5.2 may be helpful, so I'm going to try to merge those in and will submit a PR here.

**Comment by laryn** [comment]
@herbdool see https://github.com/backdrop-contrib/webform_civicrm/commit/e920e37e036b901bb012fbc777bfb1f241cf6040

**Comment by laryn** [comment]
Maybe wait on merging this due to https://github.com/colemanw/webform_civicrm/pull/364

**Comment by jackaponte** [comment]
Closing this since it was taken care of in #51!
