### ISSUE TITLE
Merge in 7.x-5.2, 7.x-5.3 and 7.x-5.4

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/webform_civicrm#51]
https://www.drupal.org/project/webform_civicrm/releases/7.x-5.2
https://github.com/colemanw/webform_civicrm/compare/7.x-5.1...7.x-5.2

https://www.drupal.org/project/webform_civicrm/releases/7.x-5.3
Fixes a regression saving custom data: https://github.com/colemanw/webform_civicrm/pull/364

https://www.drupal.org/project/webform_civicrm/releases/7.x-5.4
https://github.com/colemanw/webform_civicrm/compare/7.x-5.3...7.x-5.4

**Comment by jackaponte** [comment]
I hope to get have a PR ready for this by the end of next week.

**Comment by jackaponte** [comment]
Actually I was able to get a PR created and tested today! @herbdool the PR is ready for your review when you've got time.

**Comment by herbdool** [comment]
@jackaponte thank you! Merged and released.

**Comment by jackaponte** [comment]
Great, thanks for the release @herbdool!
