### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform_civicrm#54]
I'm not sure if it's my server or recent changes to Backdrop caching, but I've been noticing really aggressive caching on CiviCRM webforms -- changes don't show up for a long time or until I manually clear caches. What do you think about including a node-specific cache clear upon saving changes?

From Zulip in a separate topic:

> Luckily, turns out Backdrop allows clearing cache for individual node pages with `cache('cache_entity_node')->flush();`.

**Comment by laryn** [comment]
Potentially related comment from @herbdool in a separate module's issue queue:
https://github.com/backdrop-contrib/corresponding_node_references/issues/2#issuecomment-926647167

**Comment by herbdool** [comment]
What part of the Webform is not updating? Does the problem appear with Webform even without CiviCRM?

**Comment by laryn** [comment]
@herbdool I haven't noticed it happening on the main **Webform > Components** page when adding normal components. When I add contacts in the **CiviCRM** tab and check the box on one or more fields to add to the form, it sends me back to the **Webform > Components** page but the components aren't showing until I clear the "Page and else" cache.

**Comment by herbdool** [comment]
I'm not sure if entity cache would affect this. We'd need to find out if Webform takes advantage of entity_cache at all.

**Comment by jackaponte** [comment]
> When I add contacts in the **CiviCRM** tab and check the box on one or more fields to add to the form, it sends me back to the **Webform > Components** page but the components aren't showing until I clear the "Page and else" cache.

Confirming that I've observed the same behavior!

**Comment by laryn** [comment]
This note from @indigoxela may be relevant here, too?
https://github.com/backdrop/backdrop-issues/issues/5304#issuecomment-945694679

**Comment by herbdool** [comment]
@laryn I think you were right about entity cache. Oddly github search wasn't bringing up any results when I searched for "cache" or "cache_entity_node" in this project so I was initially at a loss. Luckily a local search brought it up. Fixed https://github.com/backdrop-contrib/webform_civicrm/commit/4ee1eec37e739426f231b1f2459630e607959988. I think I'll make a patch release.
