### ISSUE TITLE
State/Province gets blanked out

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform_civicrm#61]
I've noticed on a few different sites that webforms seem to collect the state/province in the submission data, but the contact's address in CiviCRM ends up with no state/province value set.

**Comment by laryn** [comment]
I just looked on a Drupal 7 site and this doesn't seem to be happening there.

**Comment by herbdool** [comment]
Perhaps put some debugging in the submit handler or in the API call? Where is this failing?

**Comment by laryn** [comment]
@herbdool I had some time to look at this more closely today and I think I tracked it down to a section in the code that is duplicated (and not present in the Drupal 7 code). Take a [look at that PR](https://github.com/backdrop-contrib/webform_civicrm/pull/62), compared to the code here:

 - https://git.drupalcode.org/project/webform_civicrm/-/blob/7.x-5.x/includes/wf_crm_webform_postprocess.inc#L741-772

Note there's another section in this area that is not in the Drupal 7 code but I'm leaving it for now since that isn't related to this issue and may have been added intentionally:

```
          // Update Backdrop email address
          if ($location == 'email' && !empty($params['email']) && $i == 1) {
            $uid = wf_crm_user_cid($cid, 'contact');
            if ($uid) {
              $user = user_load($uid);
              if ($params['email'] != $user->mail) {
                // Verify this email is unique before saving it to user
                $args = [':mail' => $params['email']];
                if (!(db_query("SELECT count(uid) FROM {users} WHERE mail = :mail", $args)->fetchField())) {
                  user_save($user, ['mail' => $params['email']]);
                }
              }
            }
          }
```

**Comment by herbdool** [comment]
@laryn I believe that 7.x-5.7 will fix this issue. Looks like all the fixes in this release includes this file. https://github.com/backdrop-contrib/webform_civicrm/releases/tag/1.x-5.7.0

**Comment by laryn** [comment]
Confirmed `1.x-5.7.0` seems to fix this issue.
