### ISSUE TITLE
Resigning as co-maintainer

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/webform_civicrm#66]
Hey @herbdool,

First, huge apologies for ghosting on you without even a heads up! Things have been a little wild for me this year, but still, not cool to disappear on your co-maintainer with no warning.

At this point, since I'm not focusing on CMS or web work anymore, it's best if I resign as a co-maintainer of this project. I can either remove myself as a designated co-maintainer in the README etc or you can, whatever you prefer.

If/when I start using the module again (I might!) I'll try my best to submit bug reports and patches as I can; I still think this module is so important!

--Jack

**Comment by herbdool** [comment]
Hi Jack, thank you for letting me know and thanks for your help! I wish you all the best in your ventures.

**Comment by jackaponte** [comment]
Thank you, Herb!
